### ISSUE TITLE
I cannot input space charater or tab charater into the code block in text editor. 

### ISSUE THREAD

**Issue by chncho** [zadam/trilium#1183]
I cannot input space charater or tab charater into the code block in text editor. Like this 

![2020-08-11_10-51](https://user-images.githubusercontent.com/6135686/89852350-386c1580-dbc1-11ea-8d36-19fc7a5e49c1.png)

version : 0.43.3
system : ubuntu 20.04

**Comment by chncho** [comment]
the picture is break , upload another one as blow

![2020-08-11_10-51](https://user-images.githubusercontent.com/6135686/89852472-7d904780-dbc1-11ea-9606-9336702cbd66.png)

**Comment by zadam** [comment]
Hmm, that's certainly weird. I can't reproduce this, I'm also on ubuntu 20.04 ...

**Comment by chncho** [comment]
![2020-08-12-001](https://user-images.githubusercontent.com/6135686/89986720-88290a80-dcaf-11ea-9a71-a7588ec46b3a.png)

It looks like this @zadam

**Comment by chncho** [comment]
I found the key point to this , as a defined the css like below. The both brings odd behaver to the code block in the text editor and the code type note. But the last year , I also has these css, but doesn't bring odd behaver. @zadam 
``` css
code{
    white-space: nowrap;
}
.CodeMirror-wrap pre.CodeMirror-line span, .CodeMirror-wrap pre.CodeMirror-line-like span{
    word-wrap: break-word;
    white-space: nowrap;
    word-break: normal;
}
```

![2020-08-13-001](https://user-images.githubusercontent.com/6135686/90084183-48adfd00-dd47-11ea-9d26-28f6e54ba22b.png)
