### ISSUE TITLE
Need to refresh page each time I create/edit a note

### ISSUE THREAD

**Issue by aashish108** [zadam/trilium#1347]
Hi there! Got a small but annoying issue where, when creating a new note or editing an existing one, I have to refresh the browser to see the changes! Not sure what's up.

# Info
Version: 0.45.1
[trilium-2020-10-28.log](https://github.com/zadam/trilium/files/5453708/trilium-2020-10-28.log)

Cheers

**Comment by zadam** [comment]
Hi, this is a common issue. You apache/nginx/whatever is misconfigured and blocks the WebSocket traffic which is important for correct functioning of the app.

**Comment by aashish108** [comment]
I see, thanks @zadam . How is this supposed to work in docker? Externally, a domain points to my server and it terminates at a reverse proxy which points it to a docker via port 8600 and, internally, goes to port 8080. So not sure which websocket should be available externally?

```
trilium:
    image: zadam/trilium:latest
    restart: always
    ports:
      - 8600:8080
    environment:
      - TRILIUM_DATA_DIR=/data
    volumes:
      - ${TRILIUM_DATA_FOLDER}:/data
    networks:
      - trilium-net
```

Thanks!
