### ISSUE TITLE
(Bug report) Custom themes not loaded in 0.48.0-beta

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#2220]
Just switched to the new 0.48.0-beta.

I have my own custom theme, and adjusted it as mentioned in the release notes. But I can't get Trilium to apply the theme - it stays with the default white theme look, and my theme changes don't make any difference.

I included part of my theme CSS code below. Maybe I overlooked some adjustments?

**Platform**
 - Running on Windows
 - Using combination of server and desktop, where the desktop syncs to the server? 
 - Version 0.48.0-beta
 - 0.48.0-beta Docker image used to run the server

```css
:root {
    --theme-style: dark;

    --main-font-family: 'Open Sans', 'Verdana';
    --main-font-size: 13pt;
    --tree-font-family: inherit;
    --tree-font-size: 12pt;
    --detail-font-family: inherit;
    --detail-font-size: normal;
    --detail-text-font-family: 'Open Sans', 'Calibri';
    --monospace-font-family: Consolas;
    --monospace-font-size: normal;

    --main-background-color: #ccc;/* #404552;*/
    --main-text-color:  #BFC8D6; /* #AFB8C6; */
    --main-border-color: #686778;
    --accented-background-color: #383C4A;
    --more-accented-background-color: #2F343F;
    --header-background-color: #383C4A;
    --button-background-color: #2F343F;
    --button-disabled-background-color: #404552;
    --button-border-color: #333;
    --button-text-color: #AFB8C6;
    --button-border-radius: 2px;
    --primary-button-background-color: #6c757d;
    --primary-button-text-color: white;
    --primary-button-border-color: #6c757d;
    --muted-text-color: #86919F;
    --input-text-color: #AFB8C6;
    --input-background-color: #404552;
    --hover-item-text-color: white;
    --hover-item-background-color: #4877B1;
    --active-item-text-color: white;
    --active-item-background-color: #4877B1;
    --menu-text-color: #AFB8C6;
    --menu-background-color: #383C4A;
    --tooltip-background-color: #383C4A;
    --link-color: lightskyblue;
    --modal-background-color: #404552;
    --modal-backdrop-color: black;
    --scrollbar-border-color: rgba(175, 184, 198, 0.5);
}

/* editor markup */
body .note-detail-text h1, h2, h3, h4, h5, h6 {
    color: #99DD33; 
    margin-top: 3ex !important;
    margin-bottom: 1ex !important;
    padding: .2ex .5ex;
}

...
```
