### ISSUE TITLE
(Bug report) Docker Compose file needs to be updated

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [zadam/trilium#2239]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

latest

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Ubuntu live server 20.10

### Expected Behavior

To have data in data-Folder. 

```
version: '2.1'
services:
  trilium:
    build:
      context: .
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "8080:8080"
    volumes:
      - trilium:/data

volumes:
  trilium:
```

Neither `- TRILIUM_DATA_DIR=/data` nor `volumes: - trilium:/data` does anything meaningful. The data folder is empty and recreated everytime the docker image is recreated -> It stores the data inside the container itself. 

### Actual Behavior

Empty data folder

**Comment by Unrepentant-Atheist** [comment]
Solution: `chown 1000:1000` the trilium volume.

**Comment by zadam** [comment]
Hi, I'm not sure what exactly needs to be fixed. Would you mind creating a PR?

Thanks.

**Comment by zadam** [comment]
I see. This file was contributed externally as a sort of example, maybe it's missing e.g. the exact directory mapping which needs to be filled by the end-user.

If the file is more confusing than helpful I might just delete it.

**Comment by Mist-Hunter** [comment]
Thank you for Trilium, it is one the best note taking apps I have ever seen, really awesome. 

I just want to add in here, that ```TRILIUM_DATA_DIR``` as seen in the [docker-compose.yml](https://github.com/zadam/trilium/blob/master/docker-compose.yml) doesn't seem to be supported by the script logic anywhere outside of /home/node

Looking at [start-docker.sh](https://github.com/zadam/trilium/blob/master/start-docker.sh)

```bash
#!/bin/sh

[[ ! -z "${USER_UID}" ]] && usermod -u ${USER_UID} node || echo "No USER_UID specified, leaving 1000"
[[ ! -z "${USER_GID}" ]] && groupmod -g ${USER_GID} node || echo "No USER_GID specified, leaving 1000"

chown -R node:node /home/node
exec su-exec node node ./src/www
```

The only chown in the containers code that doesn't run after ```exec su-exec node node``` is ```chown -R node:node /home/node```

In my mind ```chown -R node:node /home/node``` should be changed to ```chown -R node:node $TRILLIUM_DATA_DIR``` or another line should be added to include ```chown -R node:node $TRILLIUM_DATA_DIR```.

I believe what is happening in number of [open issues](https://github.com/zadam/trilium/issues?q=is%3Aissue+is%3Aopen+mkdir+permission+denied+), is ```mkdir``` is correctly getting called to create (as an example) ```$TRILLIUM_DATA_DIR/logs``` but it fails because the whole container is running under the ```root``` user and the ```$TRILLIUM_DATA_DIR``` is mounted with ```root``` permissions, but ```mkdir``` and other commands are running under ```node``` at 1000 or $USER_UID / $USER_GID.

**Comment by zadam** [comment]
> In my mind `chown -R node:node /home/node` should be changed to `chown -R node:node $TRILIUM_DATA_DIR` or another line should be added to include `chown -R node:node $TRILIUM_DATA_DIR`.

This shouldn't matter - `$TRILIUM_DATA_DIR` is actually empty in the docker container and the whole `/home/node` ownership is being changed to `node` user. `trilium-data` is then created within `/home/node`, all with `node` user ownership ...

The container is starting as root user, but changing immediately to run under `node` user ...

**Comment by Mist-Hunter** [comment]
Thanks for the quick reply, I thought that ```$TRILIUM_DATA_DIR ``` was able to point anywhere (as am example, I was using /config) and mkdir seemed to be choking on creating a ```/``` path. I must have been looking at it wrong. 

The compose below is an example of what I (and I think a few others) we trying to do with ```$TRILIUM_DATA_DIR```.

```yml

version: '2.1'
services:
  trilium:
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "8080:8080"
    volumes:
      - trilium:/data

volumes:
  trilium:
  ```
