### ISSUE TITLE
(Feature request) Bring back Zen Mode

### ISSUE THREAD

**Issue by en3r0** [zadam/trilium#2572]
### Describe feature

I personally found Zen Mode to be a great way to focus in on the notes.

Is there any way to bring it back?

**Comment by zadam** [comment]
Hi, if you hide the left panel, there isn't that much visible on the screen:

![image](https://user-images.githubusercontent.com/617641/149830453-ecda9c44-aecc-461a-b922-d41787f11e78.png)

**Comment by en3r0** [comment]
I agree, it is not much, but it is not quite "zen like".

Ideally I would like to get as close to a blank screen as possible. All icons and tabs hidden, just a blank screen and a blinking cursor.

I don't think something like that is possible through CSS modification only?

**Comment by zadam** [comment]
> I don't think something like that is possible through CSS modification only?

Almost. You can hide the elements on the page with CSS selectors, but you also need a way to trigger between zen and non-zen mode.

You could add a button/shortcut like this:

```javascript
api.addButtonToToolbar({
    title: 'Zen mode',
    icon: 'book',
    action: function() {
         $("body").toggleClass("zen-mode");
    },
    shortcut: 'alt+t'
});
```

The hiding CSS selectors will be then prepended with `.zen-mode`.

**Comment by cwilliams5** [comment]
Zadam's way above works excellent! I've added Zen Mode to my [Midnight Trilium Theme](https://github.com/cwilliams5/Midnight-Trilium-Dark-Mode), but heres the relevant CSS I used.

For a basic Zen Mode that still keeps some note UI like tabs, attributes, and splitter:
```css
/* Zen Mode */
body.zen-mode #launcher-pane, body.zen-mode #left-pane, body.zen-mode .title-bar-buttons {
    display:none !important;
}
```

For an extreme Zen Mode that hides everything but the note:
```css
/* Zen Mode Extreme */
/* display:none friendly */
body.zen-mode #launcher-pane, body.zen-mode #left-pane {
    display:none !important;
    height:0 !important;
    width:0 !important:
} 
/* display:none not friendly - some of these have an interactivity lag when coming back from display:none so another method must be used */
/* even this isn't 100% fix, delay still happens sometimes, but less often and for less length in time */
body.zen-mode .title-bar-buttons, body.zen-mode .tab-row-widget, body.zen-mode .title-row, body.zen-mode .ribbon-top-row, body.zen-mode .gutter, body.zen-mode #rest-pane > div:nth-child(1) {
    display:none !important;
    height:0 !important;
    width:0 !important:
} 
```
