### ISSUE TITLE
SqLightError after restart

### ISSUE THREAD

**Issue by MrToast72** [zadam/trilium#2676]
I seem to be having an issue with my trilium server after I rebooted it last night. Ever since then I get spammed with this error message from the logs. 

```

SqliteError: disk I/O error
    at Database.pragma (/usr/src/app/node_modules/better-sqlite3/lib/methods/pragma.js:10:27)
    at Object.<anonymous> (/usr/src/app/src/services/sql.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/src/services/notes.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
``` 

My compose file
```
version: '3'
services:
  trilium:
    image: zadam/trilium
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    container_name: Trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "82:8080"
    volumes:
      - triliumdata:/data
volumes:
  triliumdata:

networks:
  default:
    external:
      name: hostnames
```

Computer info
```
Windows server 2019
VM Gen 2 running Debian 11 with docker and docker compose only
50gb of ram allocated to VM
40 Corese from my 2X Xeon processor allocated to VM
200GB of SSD storage allocated to VM
```

Not sure where to go from here, any help is appreciated.
