### ISSUE TITLE
(Feature request) Change Scrollbar color

### ISSUE THREAD

**Issue by en3r0** [zadam/trilium#2709]
### Describe feature

I imagine I am missing something, but is it possible to change the scrollbar color via CSS?

I can see that the border color is changeable, but cannot figure out how to change the background color of the scrollbar itself.

**Comment by zadam** [comment]
There is some vendor specific support for styling scrollbars, this is what Trilium uses:

```css
::-webkit-scrollbar {
    width: 12px;
}

::-webkit-scrollbar-thumb {
    border-radius: 3px;
    border: 1px solid var(--scrollbar-border-color);
    background-color: var(--main-background-color);
}

::-webkit-scrollbar-corner {
    background-color: inherit;
}
```
