### ISSUE TITLE
(Feature request) Ability to scroll a few lines after the end of the document

### ISSUE THREAD

**Issue by VaiOnko** [zadam/trilium#2728]
### Describe feature

Now, when adding math at the end of a long document, the math box goes off screen and can't be seen. The workaround is to add a few empty lines after, but this issue could be easily fixed by adding the ability to scroll  further, like for example getting the last line of the text to the middle of the screen, like Joplin does it. 

Doesn't sound too hard to implement to me, but hard enough that I can't do it.

**Comment by pingumen96** [comment]
Hello, I think that the only thing that is needed is some padding in the end of the document, I'd like to work on it but I don't have time to do it
![image](https://user-images.githubusercontent.com/11261364/197210237-440fa99d-d9e4-4a4f-950d-92b71db37ca3.png)
I only added some padding as you can see

**Comment by zadam** [comment]
@pingumen96 it's actually more complex than that. There are other panes/view which can appear there if there's available space (e.g. children overview, mermaid preview etc.). Having artificial padding there would disrupt this.

**Comment by mechanarchy** [comment]
A hacky solution that works for me; this just adds some padding (suboptimal solution as identified above) to the bottom of text and code notes. It definitely does put a weird gap in before the children overview, but I can deal with that minor inconvenience for the huge quality-of-life improvement it brings me.

Create a CSS code note with attribute `appCss` and the following content:
```css
/*
Allow overscrolling the text & code note editors
*/
.note-detail-editable-text-editor, .note-detail-readonly-text {
    padding-bottom: 5em !important;
}
.CodeMirror-code {
    /* This slightly breaks the vscroll bar, but idc */
    padding-bottom: 5em;
}
```
