### ISSUE TITLE
(Feature request) Can you make the menu column on the left support moving to the top horizontally, and the logo becomes the default color instead of moving the mouse to color it? 

### ISSUE THREAD

**Issue by oreak** [zadam/trilium#2734]
### Describe feature

Can you make the menu column on the left support moving to the top horizontally, and the logo becomes the default color instead of moving the mouse to color it?

**Comment by XXXJetfireXXX** [comment]
(我正在使用翻译器)
1) 不确定问题的第一部分是什么意思。 如果我理解正确的话，左边的列表可以通过在此处移动光标来水平展开：
![image](https://user-images.githubusercontent.com/43646178/159149332-fbdb17ce-e7d4-46ad-b2de-cdf399167adb.png)
您可以通过单击此处完全隐藏它:
![image](https://user-images.githubusercontent.com/43646178/159149396-62369a59-bd0a-4c58-8cb9-4218554a40bc.png)


2) 你可以用你自己的风格做到这一点： https://github.com/zadam/trilium/wiki/Themes
您需要将以下代码添加到您的 CSS 文件中：
```css
body .global-menu-button{
    background-image: url("../../../images/icon-color.png");
}
```
