### ISSUE TITLE
Make window with search results wider.

### ISSUE THREAD

**Issue by Rigel772** [zadam/trilium#2775]
### Describe feature

At the moment the search results are displayed in window like on the picture:
https://i.imgur.com/iZAeDdy.png
Maybe it would be good idea to make this window wider? Eg full trillium window wide?

That would help analyzing thte search results.

Otherwise the app works great!! Fantastic work

**Comment by XXXJetfireXXX** [comment]
You can change its size by using this css code in a custom theme:
```css
.quick-search .dropdown-menu {
    max-height: 600px;
    max-width: 400px;
}
```
![image](https://user-images.githubusercontent.com/43646178/162042037-43cb41cd-8b1e-4179-aa9c-ca9c37722abf.png)
