### ISSUE TITLE
Docker : Can't run by using user 1000:1000

### ISSUE THREAD

**Issue by patchint** [zadam/trilium#3045]
### Trilium Version

zadam/trilium:0.54-latest

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Server : Debian 5.10.127-1 Desktop : ArchLinux 5.18.16-arch1-1

### Description

Hi

I was trying to use Trilium by using docker-compose and I saw that I can't run by using the user 1000:1000.

That's my configuration : 
```  yml
  trilium:
    image: zadam/trilium:0.54-latest
    user: 1000:1000
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETUID
      - CAP_SETGID
    volumes:
      - ./applications/trilium:/home/node/trilium-data
    networks:
      - no-internet
    security_opt:
      - apparmor=docker-default 
      
```

docker-compose logs -f trilium
```
docker-trilium-1  | No USER_UID specified, leaving 1000
docker-trilium-1  | No USER_GID specified, leaving 1000
docker-trilium-1  | su-exec: setgroups: Operation not permitted
```

If I remove the CAP drop and the CAP add, I had the same issue

**Comment by DynamoFox** [comment]
I think you're supposed to change the uid and gid by setting the 'USER_UID' and 'USER_GID' environmental variables in the Composefile to the user/group numerical id you choose. Then start_docker.sh (which is the first file executed in the container) will take care of setting the new ownership of Trilium's data and will run its process with the specified user and group.

**Comment by patchint** [comment]
I don't use the script to run it :|

And when I set envrionnement variables, I got this error

Terminal output
```
root@marisa:~/Docker# docker-compose up -d 
services.trilium Additional property environnement is not allowed
```
```yml
    environnement:
      - USER_UID=1000
      - USER_GID=1000
```

But it's already using 1000:1000 in the bash script I guess, and that's by building myself the docker image that I have to use the script

DockerFile
```Dockerfile
35 - CMD [ "./start-docker.sh" ]
```

And I can't use any environnement variables because there is no environnement variables in the Dockerfile, so I guess the docker-compose.yml is false because it set by default the TRILIUM_DATA_DIR and I think it's a deprecated feature of this project if you use Docker

```yml
  version: '2.1'
  services:
    trilium:
      build:
        context: .
      image: zadam/trilium
      restart: always
      environment:
        - TRILIUM_DATA_DIR=/data
      ports:
        - "8080:8080"
      volumes:
        - trilium:/data
  
  volumes:
    trilium:
```

So actually to get it running correctly I recommend to use this config if you use the image available on DockerHub : 

```yml
version: "3.9"
services:
  trilium:
    image: zadam/trilium:0.53-latest
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETUID
      - CAP_SETGID
    volumes:
      - ./applications/trilium:/home/node/trilium-data
    ports:
     - 8080:8080
    security_opt:
      - apparmor=docker-default
```
