### ISSUE TITLE
(Bug report) Missing grey Trilium icon while using custom css theme

### ISSUE THREAD

**Issue by Lightirius** [zadam/trilium#3377]
### Trilium Version

0.57.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 21H2

### Description

I have a custom dark theme for Trilium and after update to 0.57.3 grey Trilium icon is no longer displayed on menu button.

On 0.56.2 it worked fine with this css for button background:
```css
body .global-menu-button {
    background-image: url(/images/icon-grey.png);
}
```
Without this css black Trilium icon is displayed on both 0.57.3 and 0.56.2

To reproduce:

1. Copy default dark-theme.css to css note
2. Add #appTheme=test to it
3. Enable theme in the settings

Actual result:
![image](https://user-images.githubusercontent.com/11685338/205433179-53454f80-98eb-419a-8ed9-cb94499a698e.png)

Expected result:
Theme looks exactly the same as default dark theme

As I can see - this is a side effect of moving assets to versioned path.
For example this css works on 0.57.3, but it depends on Trilium version, so custom theme must be updated on every Trilium update:
```css
body .global-menu-button {
    background-image: url("/assets/v0.57.3/images/icon-grey.png");
}
```

**Comment by zadam** [comment]
Hi, for these cases there's a fixed variant of the asset path:

```css
body .global-menu-button {
    background-image: url("/assets/vX/images/icon-grey.png");
}
```

https://github.com/zadam/trilium/wiki/Themes#asset-path
