### ISSUE TITLE
Docker Compose + Nginx reverse proxy: error 502 Bad Gateway, Connection reset by peer

### ISSUE THREAD

**Issue by Andrewskiz** [zadam/trilium#3558]
Hey, I just installed Trilium via Docker Compose and I am having trouble with nginx and a reverse proxy. 

Here is my docker-compose.yml (I changed the port since I have another service running on port 8080)

```
version: '2.1'
services:
  trilium:
    image: zadam/trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - "127.0.0.1:8050:8050"
    volumes:
      - trilium:/home/node/trilium-data

volumes:
  trilium:

```

and the reverse proxy section in my nginx config:

```
location /trilium/ {
    proxy_pass http://127.0.0.1:8050/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}
```

There are no errors in the docker container logs, and this is the status on docker:

```
CONTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS                  PORTS                                NAMES
************   zadam/trilium                 "docker-entrypoint.s…"   23 hours ago   Up 23 hours (healthy)   127.0.0.1:8050->8050/tcp, 8080/tcp   triliumdocker_trilium_1
```

When I try to visit https://mydomain.com/trilium/ I get error 502 Bad Gateway. This is the error I am getting in my nginx log:

`2023/01/24 17:12:01 [error] 1110637#1110637: *1565 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 24.246.165.241, server: mydomain.com, request: "GET /trilium/ HTTP/1.1", upstream: "http://127.0.0.1:8050/", host: "mydomain.com"`

I'm still new to docker and reverse proxies, so I've probably made a error somewhere. Any help would be greatly appreciated,  thank you!
