### ISSUE TITLE
(Bug report) Docker in rootless mode still not working

### ISSUE THREAD

**Issue by mezklador** [zadam/trilium#3646]
### Trilium Version

latest

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Debian 11

### Description

Hi,

I tried to install on my production server, running on OVH's infrastructure, under Linux Debian 11, Trilium on a rootless version of Docker's Community Edition.

I have setup the instance via docker-compose's file, like this:

```
version: "3.3"
services:
  trilium:
    image: zadam/trilium:latest
    container_name: trilium-notes
    environment:
      - "USER_UID=500000"
      - "USER_GID=500000"
    volumes:
      - /home/boss/Dockers/trilium-notes/data:/home/node/trilium-data
    ports:
      - 0.0.0.0:8880:8080
 ```

As you van notice, I insert the User's ID and GID within the environment, as you advice to.

But when I launch the command, it's existed and nothing run, unfortunatly.

It seems that your script tried to `chown` the data directory in a wrong way (see logs).

Or maybe, I haven't done things wisely?

Thank you for any tips abour this issue.

### Error logs

```
No USER_UID specified, leaving 1000
usermod: Failed to change ownership of the home directorychown: /home/node/trilium-data: Invalid argument
chown: /home/node/trilium-data: Invalid argument
chown: /home/node: Invalid argument
chown: /home/node: Invalid argument
su-exec: setgroups: Invalid argument
usermod: no changes
chown: /home/node/trilium-data: Invalid argument
chown: /home/node/trilium-data: Invalid argument
chown: /home/node: Invalid argument
chown: /home/node: Invalid argument
su-exec: setgroups: Invalid argument
```
