### ISSUE TITLE
Every day generate a root log?(Bug report) 

### ISSUE THREAD

**Issue by holoword** [zadam/trilium#3677]
### Trilium Version

0.59.1

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Ubuntu 20.04.4 LTS

### Description

After update to 0.59.1, trilium server generate a daily log belong to root, cause the server failing and exit, the error is same as #1971 , after chown the file belong, the server can restart and work correctly.

the configure of my trilium below:
```
version: '3'
services:
  trilium:
    container_name: otrilium
    image: zadam/trilium
    restart: always
    environment:
      USER_UID: 1001
      USER_GID: 1001
      LOG_FILE: ./trilium.log
      TZ: 'Asia/Shanghai'
      TRILIUM_DATA_DIR: /data
    volumes:
      - ./trilium-data/:/data
```

the daliy log of 2023.03.06 last min is ok 
```
23:57:56.169 200 GET /api/health-check with 15 bytes took 1ms
23:58:26.307 200 GET /api/health-check with 15 bytes took 0ms
23:58:56.448 200 GET /api/health-check with 15 bytes took 0ms
23:59:26.584 200 GET /api/health-check with 15 bytes took 1ms
23:59:56.722 200 GET /api/health-check with 15 bytes took 1ms
```
but after 00.00 throw the the permession error of new log file.

### Error logs

[trilium-2023-03-06.log](https://github.com/zadam/trilium/files/10905221/trilium-2023-03-06.log)
