### ISSUE TITLE
Suggestion: Code Block Formatting

### ISSUE THREAD

**Issue by Abourass** [zadam/trilium#386]
When you use code blocks right now they are wrapped in paragraphs, causing a rather untidy look. The following CSS makes it appear as if they were not wrapped in paragraphs:
```css
.ck-content code {
    background-color: #785d8e3d;
    padding: 0.4rem 0.1em;
    border-radius: 0px;
    margin-top: -0.3rem;
    font-size: 95%;
    line-height: 110%;
    white-space: pre;
    white-space: pre-wrap;
    display: -webkit-box;
}
```
Example:
![Example picture of modified Code Block](https://i.imgur.com/0qed4j3.png)
--------------------

**Pros:**
* Looks much tidier
* Long Code Blocks are much easier to read

**Cons:**
* Inlining code examples cause a break to new line from box display. (I just use italics instead as shown in picture above)
