### ISSUE TITLE
colorful tree

### ISSUE THREAD

**Issue by LordSouza** [zadam/trilium#3892]
### Describe feature

is it possible to make a colorful tree? because the tree becames really hard to see when i work with a project that has a lot of folders open
![image](https://user-images.githubusercontent.com/79264145/235378179-0d6bb7e1-14b4-4e45-88a4-5b16110f015e.png)
i want something like vscode that shows a little line or different color 
![image](https://user-images.githubusercontent.com/79264145/235378208-51eb28d8-5024-40b7-9ac1-1c92c73b408b.png)

**Comment by Nriver** [comment]
Try dd tag #color=red to your note

**Comment by LordSouza** [comment]
I found a way with CSS

```
/* this is to make symmetrical */
.ui-fancytree > li > ul{
    padding-left: 20px;
}
ul.fancytree-container li{
    box-shadow: inset 3px 0 0px 0 #00ADB5
}
```

will look like this:
![image](https://user-images.githubusercontent.com/79264145/235521448-e14bb2d4-f5e5-4ce3-a41c-8bca83944c1f.png)

**Comment by Nriver** [comment]
Ah, you want the vertical lines. Then  you must try this theme https://github.com/SiriusXT/trilium-theme-blue

**Comment by grosserfrank** [comment]
Oh thanks

**Comment by banjuer** [comment]
> Neat. Thanks for reporting back 👍
> 
> Here's my more subtle copy of yours. It removes the leftmost line and makes the vertical bars very subtle (on dark mode at least).
> 
> ```
> /* this is to make symmetrical */
> .ui-fancytree > li > ul{
>     padding-left: 20px;
> }
> .fancytree-lastsib li{
>     box-shadow: inset 1px 0 0px 0px #333333
> }
> ```

can we make different color between dark and white theme?

**Comment by LordSouza** [comment]
> > Neat. Thanks for reporting back 👍
> > Here's my more subtle copy of yours. It removes the leftmost line and makes the vertical bars very subtle (on dark mode at least).
> > ```
> > /* this is to make symmetrical */
> > .ui-fancytree > li > ul{
> >     padding-left: 20px;
> > }
> > .fancytree-lastsib li{
> >     box-shadow: inset 1px 0 0px 0px #333333
> > }
> > ```
> 
> can we make different color between dark and white theme?

probably, but you gonna need to know the css class names to reference there and create some condition [here's a link how, but idk if that's gonna work](https://stackoverflow.com/questions/1129699/can-you-use-if-else-conditions-in-css), and make one for each, I didn't dive too deep in this, so I can't help you with it.

**Comment by connectluole** [comment]
![image](https://github.com/user-attachments/assets/40eeaab2-1ce8-4e84-a6fc-62c4e63c1674)

/*----- make the lef pane tree has one vertical line */
.ui-fancytree > li > ul{
    padding-left: 20px;
}
.fancytree-lastsib li {
    border-left: 1px solid #cccccc;
    border-radius: 5px 0 0 5px;
}

**Comment by linull24** [comment]
It's my fix for **TriliumNext** . My notes is with complex structure so it is necessary.

![Image](https://github.com/user-attachments/assets/b352a537-cf20-41fd-b336-ee86c5c92006)

```css
.fancytree-node {
    padding: 2px 2px !important;
    height: 38px !important;
    line-height: 1.2 !important;
    margin-bottom: 2px !important;
}

.fancytree-title {
    margin-left: 2px !important;
    top: 2px !important;
}

.fancytree-node:not(.fancytree-loading) .fancytree-expander:before {
    margin-right: 2px !important;
    font-size: medium !important;
    top: 2px !important;
}

.ui-fancytree > li > ul {
    padding-left: 2px !important;
}

.ui-fancytree ul {
    padding-left: 10px !important;
}

.fancytree-lastsib li {
    border-left: 2px solid #00ADB5 !important;
    border-radius: 5px 0 0 5px !important;
}

.bx.tree-item-button {
    margin-left: 4px !important;
    font-size: 100% !important;
    padding: 1px !important;
}

.fancytree-loading span.fancytree-expander {
    margin: 2px 4px 0 2px !important;
    width: 14px !important;
    height: 14px !important;
    border: 2px solid var(--main-text-color) !important;
    border-radius: 50% !important;
    animation: lds-dual-ring 1.2s linear infinite !important;
}

.fancytree-node {
    display: flex !important;
    align-items: center !important;
    justify-content: flex-start !important;
}

.fancytree-title {
    white-space: nowrap !important;
    overflow: hidden !important;
    text-overflow: ellipsis !important;
}
```
s

**Comment by 9acca9** [comment]
@linull24 
Hi, sorry my dumb question but.... how i can add that to my default theme in Trilium Next? (i use the TriliumNext beta dark mode).
What i need to do?
thanks.

**Comment by linull24** [comment]
> [@linull24](https://github.com/linull24) Hi, sorry my dumb question but.... how i can add that to my default theme in Trilium Next? (i use the TriliumNext beta dark mode). What i need to do? thanks.

RTFM

**Comment by KASAUSI** [comment]
> [@linull24](https://github.com/linull24) Hi, sorry my dumb question but.... how i can add that to my default theme in Trilium Next? (i use the TriliumNext beta dark mode).你好，抱歉我的问题有点蠢，但是……我该如何将这个添加到 Trilium Next 的默认主题中？（我使用的是 TriliumNext 的暗黑模式 beta 版）。 What i need to do?我需要做什么？ thanks.  谢谢。

step1: creat a new note
step2: select the note as CSS
step3: copy the code from above and paste it to the note you just created
step4: type"#appCss" in "Owned Attributes" and Ctrl+R to refresh the page
and there you go

**Comment by rami-shalhoub** [comment]
I wrote a code inspired from [Trilium Theme Blue](https://github.com/SiriusXT/trilium-theme-blue), but I made it that the tree line will show only when the tree is expanded, in my opinion this looks cleaner 

one thing I wish I could do is making the line colour follows the note colour, but unfortunately I couldn't do that because the line was applied to the `li` tag while the colour value is in the `span` under the `li`. If anyone knows how to do it you are my hero 
<details><summary>the CSS code</summary>

```css
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:nth-of-type(6n){
  border-left: 2.5px solid rgba(199, 145, 12, 0.5);
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:nth-of-type(6n+1) {
  border-left: 2.5px solid rgba(212, 110, 192, 0.5);
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:nth-of-type(6n+2) {
  border-left: 2.5px solid rgba(17, 183, 212, 0.5);
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:nth-of-type(6n+3) {
  border-left: 2.5px solid rgba(168, 95, 241, 0.5);
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:nth-of-type(6n+4) {
  border-left: 2.5px solid rgba(56, 199, 189, 0.5);
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:nth-of-type(6n+5) {
  border-left: 2.5px solid rgba(198, 47, 82, 0.5);
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}
```
</details> 

<img width="539" height="914" alt="Image" src="https://github.com/user-attachments/assets/f4f2c5d9-dc3a-4d5c-9efc-5c8ffb1ae28b" />

**Comment by bramblebrain** [comment]
> one thing I wish I could do is making the line colour follows the note colour, but unfortunately I couldn't do that because the line was applied to the `li` tag while the colour value is in the `span` under the `li`. If anyone knows how to do it you are my hero
> the CSS code


@rami-shalhoub Using the default light theme:
/
<img width="266" height="500" alt="Image" src="https://github.com/user-attachments/assets/f0882731-2b60-4ff4-8bce-06abf9ca77ac" />

```
/* 
Vertical Tree Line

https://github.com/TriliumNext/Trilium/issues/3892#issuecomment-3781293642 
*/

div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:nth-of-type(2n){
  border-left: 2.5px solid rgba(175, 184, 198, 0.8);
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:nth-of-type(2n+1){
  border-left: 2.5px solid rgba(175, 184, 198, 0.5);
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* Color based on note */
/* COLOR 1 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-E64D4D){
  border-left: 2.5px solid #D73F4280;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 2 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-E6994D){
  border-left: 2.5px solid #AB671B80;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 3 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-E5E64D){
  border-left: 2.5px solid #747E0080;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 4 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-99E64D){
  border-left: 2.5px solid #36880080;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 5 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-4DE64D){
  border-left: 2.5px solid #008E0080;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 6 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-4DE699){
  border-left: 2.5px solid #008C4880;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 7 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-4DE5E6){
  border-left: 2.5px solid #00888B80;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 8 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-4D99E6){
  border-left: 2.5px solid #1C7BC580;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 9 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-4D4DE6){
  border-left: 2.5px solid #4D4DE680;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 10 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-994DE6){
  border-left: 2.5px solid #994DE680;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}

/* COLOR 11 */
div.tree li.fancytree-lastsib ul li[aria-expanded="true"]:has(> .color-E64DB3){
  border-left: 2.5px solid #D0359F80;
  border-top-left-radius: 10px !important;
  border-bottom-left-radius: 10px !important;
}
```

**Comment by rami-shalhoub** [comment]
@bramblebrain nice I have thought of this 👏👏👏👏
the only downside is, it wont match the colour when it is custom, and I think the only way to do it is by hard coding every possible colour which is impossible

**Comment by rami-shalhoub** [comment]
**!!!UPDATE**
I wrote a JS script that will colour the treelines dynamically

this code will check the if the tree has the colour class and convert the colour value to RGBa and darken the colour a bit

you can change
- the Alpha value to control how transparent you want the colour to be (1 is full saturation and 0 is fully transparent),
- the default tree colour (this get applied when not colour is detected)
- the darkening factor (0 is fully dark and 1 no darkening)

how to apply it:
1. create a code note and set the language to `JS Frontend`
2. add label `#run=frontendStartup`
3. copy the  JS code to the note<details><summary>JS code </summary>

        /*
          Dynamic Tree Line Coloring for Trilium Notes
        */
        
        (function () {
          const DEFAULT_COLOR = "#aaaaaa"; // color for notes with no color set
          const COLOR_CLASS_RE = /^color-([0-9A-Fa-f]{6})$/;
          const alpha = 0.7;
          const darkFactor = 0.7;
        
          //Darkening the RBG colour
          function darken(rgb) {
            return {
              r: Math.round(rgb.r * darkFactor),
              g: Math.round(rgb.g * darkFactor),
              b: Math.round(rgb.b * darkFactor),
            };
          }
        
          //convert the colour value from hexadecimal to RGBa
          function HextoRGBa(color) {
            let rgb = {
              r: parseInt(color.slice(0, 2), 16),
              g: parseInt(color.slice(2, 4), 16),
              b: parseInt(color.slice(4, 6), 16),
            };
            rgb = darken(rgb);
            return `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${alpha})`;
          }
        
          function applyAll() {
            // Target all li children of the relevant ul — not just expanded ones,
            // so we can also *clear* borders when a node collapses.
            const items = document.querySelectorAll(
              "div.tree li.fancytree-lastsib ul li",
            );
            items.forEach((li) => {
              const isExpanded = li.getAttribute("aria-expanded") === "true";
        
              if (!isExpanded) {
                // Collapsed or leaf — remove any previously applied border
                li.style.borderLeft = "";
                li.style.borderTopLeftRadius = "";
                li.style.borderBottomLeftRadius = "";
                return;
              }
        
              // Find the color class on the direct child element
              let color = DEFAULT_COLOR;
              for (const child of li.children) {
                for (const cls of child.classList) {
                  const m = cls.match(COLOR_CLASS_RE);
                  if (m) {
                    color = HextoRGBa(m[1]);
                    break;
                  }
                }
                if (color !== DEFAULT_COLOR) break;
              }
        
              li.style.borderLeft = `2.2px solid ${color}`;
              li.style.borderTopLeftRadius = "10px";
              li.style.borderBottomLeftRadius = "10px";
            });
          }
        
          function waitForTree(cb, retries = 20, delay = 100) {
            const tree = document.querySelector("div.tree");
            if (tree) {
              cb(tree);
              return;
            }
            if (retries <= 0) return;
            setTimeout(() => waitForTree(cb, retries - 1, delay), delay);
          }
        
          waitForTree((tree) => {
            applyAll();
            const observer = new MutationObserver(applyAll);
            observer.observe(tree, {
              childList: true,
              subtree: true,
              attributes: true,
              attributeFilter: ["aria-expanded", "class"],
            });
          });
        })();
    
</details>

4. reload Trilium frontend with `F5` or `Ctrl+R`

**Comment by volokasse** [comment]
For those who would like to have an alternative style for this :

<img width="371" height="881" alt="Image" src="https://github.com/user-attachments/assets/ead71c51-ff7a-4888-9734-165e442adbcf" />

``` CSS
ul.fancytree-container > li > ul li li{
    box-shadow: inset 1px 0 0px 0 var(--active-item-background-color);
    margin-left: -4px;
}
.fancytree-node {
    border-radius: 0px !important;
    transition: border .15s ease-in-out;
    border-left-width: 0px !important;
    border-top-width: 0px !important;
    border-bottom-width: 0px !important;
}
span.fancytree-node:hover {
    border-right-width: 5px !important;
}
ul.fancytree-container > li > ul .fancytree-expanded::after {
    content: '';
    display: block;
    position: absolute;
    border-left: 1px solid var(--active-item-background-color);
    height: 15px;
    top: 23px;
    left: 16px;
}
ul.fancytree-container > li > ul .fancytree-expanded::before {
    content: '';
    display: block;
    position: absolute;
    border-left: 1px solid var(--left-pane-background-color);
    height: 20px;
    width: 14px;
    bottom: 0px;
    left: 16px;
    z-index: 2;
    border-top: 1px solid var(--active-item-background-color);
}
```

**Comment by dhchcm** [comment]
very nice guys
now we need the clickable vertical lines

**Comment by rami-shalhoub** [comment]
@dhchcm what do you mean by vertical?
like this 

<img width="409" height="289" alt="Image" src="https://github.com/user-attachments/assets/3aa92529-f089-4405-905d-e7233f8e1a84" />

**Comment by droud-dev** [comment]
Here's my contribution, either create a new theme or paste into your existing theme's `#trilium-app` selector:

```css
    /* IDE-style vertical lines for the tree view levels */
    #left-pane {
        li[role="treeitem"] {
            /* Based on this script-defined set of colours: https://github.com/TriliumNext/Trilium/blob/main/apps/client/src/menus/custom-items/NoteColorPicker.tsx#L13C1-L16C3 , if overriden or updated then this will break */
            /* This would be so much easier with JS */
            &:has(> span.color-E64D4D) > ul > li::before { color: #E64D4D; }
            &:has(> span.color-E6994D) > ul > li::before { color: #E6994D; }
            &:has(> span.color-E5E64D) > ul > li::before { color: #E5E64D; }
            &:has(> span.color-99E64D) > ul > li::before { color: #99E64D; }
            &:has(> span.color-4DE64D) > ul > li::before { color: #4DE64D; }
            &:has(> span.color-4DE699) > ul > li::before { color: #4DE699; }
            &:has(> span.color-4DE5E6) > ul > li::before { color: #4DE5E6; }
            &:has(> span.color-4D99E6) > ul > li::before { color: #4D99E6; }
            &:has(> span.color-4D4DE6) > ul > li::before { color: #4D4DE6; }
            &:has(> span.color-994DE6) > ul > li::before { color: #994DE6; }
            &:has(> span.color-E64DB3) > ul > li::before { color: #E64DB3; }
            
            &:hover > ul > li::before {
                opacity: 0.6;
            }
            
            li {
                &::before {
                    display: inline-block;
                    width: 1ch;
                    left: 0;
                    position: absolute;
                    border-color: currentColor;
                    border-width: 2px;
                    border-left-style: solid;
                    content: " ";
                    opacity: 0.3;
                }
                
                &[role="treeitem"]::before {
                    top: 0;
                    bottom: 0;
                }
    
                &.fancytree-lastsib {
                    &::before {
                        /* The 4px treeitem padding is hardcoded in CSS, so if replaced then this will get wonky; +1px for character alignment, might need to fiddle if using a different font */
                        bottom: calc(var(--bs-body-line-height) * 0.5em + 5px);
                    }
                    
                    &:not(:has(> ul))::before, &:not(:has(span.fancytree-expander))::before {
                        border-bottom-style: solid;
                    }
    
                    &:has(span.fancytree-expander)::before {
                        width: 0.5ch;
                    }
                }
            }
        }
        
        .fancytree-expander {
            /* Copy the existing opacity fade effect into text colour instead */
            opacity: 1;
            color: hsl(from var(--custom-color, currentColor) h s l /0.6);
            transition: color 300ms ease-out;
    
            &:hover {
                color: var(--custom-color, currentColor);
            }
            
            &::before {
                line-height: 1rem;
                font-family: monospace !important;
                font-weight: bolder;
                padding-right: 5px;
                padding-left: 2px;
                text-shadow: -1px -1px 0 var(--left-pane-background-color), 
                    1px -1px 0 var(--left-pane-background-color), 
                    -1px 1px 0 var(--left-pane-background-color), 
                    1px 1px 0 var(--left-pane-background-color),
                    -2px -2px 0 var(--left-pane-background-color), 
                    2px -2px 0 var(--left-pane-background-color), 
                    -2px 2px 0 var(--left-pane-background-color), 
                    2px 2px 0 var(--left-pane-background-color);
            }
        }
        
        .fancytree-node {
            margin-left: 1px;
    
            /* Personally just like the +- look, don't really *have* to use these */
            &:not(.fancytree-loading):not(.fancytree-expanded) .fancytree-expander:before {
                content: "+";
            }
        
            &.fancytree-expanded .fancytree-expander:before {
                content: "-";
            }
        }
    }
```

If could be bothered, then could just attach a `click` handler/listener to the `::before`, and then could also trigger the fold/open, but that's JS land
