### ISSUE TITLE
(feature request) Full Page PDF as Default

### ISSUE THREAD

**Issue by Dwindle2234** [zadam/trilium#3954]
### Describe feature

I have hundreds of notes that are just PDF files.  I would like to be able to set a global option such that when I open one of these notes it renders them in the 'full' screen i.e. not with the file attributes expanded. There's nothing useful in those properties that I need so would prefer the screen real-estate for the PDF. I know I can click file to close them individually but this doesn't persist

![image](https://github.com/zadam/trilium/assets/120342689/1e98d650-7b27-481e-b067-27f440e73bbb)

**Comment by soulsands** [comment]
Hi, It can be implemented through [attributes](https://github.com/zadam/trilium/wiki/Attributes).
1. create a note with css type.
2. paste the code into the note. 
 ```css .hide-file-properties .file-properties-widget{
    display:none!important;
}
.show-file-properties .file-properties-widget{
    display:block!important;
}
```
3. create the attribute  `#cssClass(inheritable)=hide-file-properties` on root note or the parent note of your pdf files. 
4. reload frontend.
5. you can add the attribute `#cssClass=show-file-properties` on the specifc note expected to show the file properties.
