### ISSUE TITLE
(Feature request) Ability to hide children grid in text editor

### ISSUE THREAD

**Issue by BeatLink** [zadam/trilium#3956]
### Describe feature

It would be great if there was a way to hide children notes within the text editor. This could perhaps be accomplished by a global setting along with a per note label for granular configuration, with the per note label always overriding the parent setting

**Comment by soulsands** [comment]
Hi, similar to #3954 , attributes can help with this.

1. create a note with css type.
2. paste the code into the note. 
 ```css
 .hide-child-notes .note-list-widget{
    display:none!important;
}
.show-child-notes  .note-list-widget{
    display:block!important;
}
```
3. create the attribute  `#cssClass(inheritable)=hide-child-notes` on root note.
4. reload frontend.
5. you can add the attribute `#cssClass=show-child-notes` on the specifc note expected to show its chidren.
