### ISSUE TITLE
(Bug report) Permissions issue: Can not set UID and GId to '0'. Prevents access to network share.

### ISSUE THREAD

**Issue by theRealBassist** [zadam/trilium#4008]
### Trilium Version

0.59.4

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 

### Description

Hello!

I currently have an issue where I can not use the environment flags USER_UID=0 and USER_GID=0 at all. Upon running the container I just get an error:

```
usermod: UID '0' already exists
No USER_UID specified, leaving 1000
groupmod: GID '0' already exists
No USER_GID specified, leaving 1000
```

I currently have my Trilium volume set to a network share (this is not able to be changed. This can not be moved, and the permissions can not be changed for reasons that are not relevant here), and I need Trilium to be able to access that network share as the root user. In previous versions I had absolutely no issue doing this, but after my server experienced some downtime and I've updated and reinstalled everything, I can no longer access my database.

From what I can gather, it looks like Trilium is trying to create a new user, as opposed to being able to use an existing user, and when that creation fails it just falls back on 1000:1000. I'm not really sure how to get around this.

docker-compose (only a section as this is contained in a larger stack):

```
  trilium:
    container_name: trilium
    ports:
      - ${TRILIUM_PORT}:8080
    environment:
      - USER_UID=0
      - USER_GID=0
    volumes:
      - ${MOUNT_DIR}/trilium/data:/home/node/trilium-data
    image: 'zadam/trilium:latest'
    restart: always   
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trilium.rule=Host(`trilium.DOMAIN.TLD`)"
      - "traefik.http.routers.trilium.entrypoints=https"
      - "traefik.http.routers.trilium.tls.certresolver=myresolver"
    networks:
       - traefik_default
```
[trilium_logs.txt](https://github.com/zadam/trilium/files/11653776/trilium_logs.txt)
