### ISSUE TITLE
(Bug report) Modal and popup backgrounds not rendering correctly in Firefox 114.0.2

### ISSUE THREAD

**Issue by Ahrotahntee** [zadam/trilium#4066]
### Trilium Version

0.60.4

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Linux ahrotahntee-riven 6.3.9-arch1-1 \#1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64 GNU/Linux

### Description

After upgrading to 0.60.4, some CSS aspects are not being rendered correctly. Modals and popups appear without any background color or with inappropriate alpha values. Investigation using the browser's developer console suggests that the CSS variables are not functioning correctly

 This behavior is only apparently in Firefox 114.0.2 as Chrome 114.0.5735.198 renders normally.

![Screenshot_2023-06-29_20-08-32](https://github.com/zadam/trilium/assets/4513236/0290c3d8-ea0c-47da-a2c8-68133bb8e0fc)

![Screenshot_2023-06-29_20-08-12](https://github.com/zadam/trilium/assets/4513236/97cbc4ff-42d5-4b9b-93fa-4e6ac714648e)

![Screenshot_2023-06-29_20-07-17](https://github.com/zadam/trilium/assets/4513236/a19ceb50-0dfe-4110-bc9e-e9758e6cc764)

Further investigation suggests its related to the var(var()) nesting, as the only two instances I could find of it seem to be affected.  I have applied this CSS in an \#appCss note and it appears to work around the issue.

```css
div.tooltip-inner, div.modal-content {
  background-color: #333 !important;   
}

body.heading-style-underline .note-detail-editable-text h2,
body.heading-style-underline .note-detail-editable-text h3,
body.heading-style-underline .note-detail-editable-text h4 {
  border-bottom: 1px solid #aaa !important;
}
```

### Error logs

No errors are present in the server console, nor the browser console.
