### ISSUE TITLE
(Bug report) Options page does not initially render on Firefox

### ISSUE THREAD

**Issue by fuzzykiller** [zadam/trilium#4165]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 22H2, macOS Big Sur, …

### Description

Inside Firefox, when opening the options page (the one that has tiles for _Appearance_, _Shortcuts_, …), it does not display its contents initially. That is, the HTML element `<div class="note-list-widget-content">` is completely empty. The page can be made to appear by refreshing the application (<kbd>F5</kbd>) or by switching to another note tab, then switching back. _Sometimes_ it also renders right away, but only _once_ after the web app is loaded.

I use Firefox 116.0.2 on all devices. I have replicated this behavior on Windows, macOS and Linux. It also happens with a fresh installation (see `docker-compose.yml` below). I did not get the error with Edge or Chrome or the Trilium desktop app.

My guess is that there is some sort of race condition. However, there is no error being logged.

---

Docker Compose setup that I used to test this:

```yaml
version: "3"

services:
  trilium:
    image: zadam/trilium:0.60.4
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./trilium-data:/home/node/trilium-data
```
