### ISSUE TITLE
(Bug report) Trilium detects desktop with touchscreen as mobile device

### ISSUE THREAD

**Issue by ReinforceZwei** [zadam/trilium#4316]
### Trilium Version

0.61.9-beta

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 21H2

### Description

Text in tree is larger than usual when accessing on Web. Desktop is not affected. Tested on latest release (0.60.4) and beta (0.61.9) and both version have the issue.

### Desktop (normal size)
![image](https://github.com/zadam/trilium/assets/39955851/5dc9aeb5-f422-4bc4-ade8-7aa99a67e9bf)

### Web
![image](https://github.com/zadam/trilium/assets/39955851/4d6907c7-3a1b-45ad-a06a-d13f2c89d6f7)

(Advanced option is shown even when mouse is not hovering on it)
![image](https://github.com/zadam/trilium/assets/39955851/14b0bb49-4412-42f0-ba59-ef3148177b81)

### Server setup
```yml
version: '3'
services:
  app:
    image: 'zadam/trilium:0.61.9-beta'
    restart: unless-stopped
    ports:
      - '8031:8080'
    volumes:
      - ./data:/data
    environment:
      - TRILIUM_DATA_DIR=/data
```
