### ISSUE TITLE
(Bug report) Unable to store attachments larger than 250 MB

### ISSUE THREAD

**Issue by miltuss** [zadam/trilium#4718]
### Trilium Version

0.63.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Debian server

### Description

Hello, I use trilium (docker) only with the web client on my server, but I cannot disable the file size limit set to 250 MB.  However, I added the following environment variable in the docker-compose file
 `- TRILIUM_NO_UPLOAD_LIMIT=1` 
 I also added it to the trilium config.ini file, but the 250MB limit has still not been deactivated!

 How to disable this restriction?

**Comment by Nriver** [comment]
It works on my machine. I guess you did not set it right.

**Comment by miltuss** [comment]
> It works on my machine. I guess you did not set it right.
> 
> Just tested a big file, works fine. ![snipaste20240330_184721](https://private-user-images.githubusercontent.com/6752679/318187934-5eeb5747-6222-47ac-95d2-0d21e619b005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTc2MDcsIm5iZiI6MTcxMTc5NzMwNywicGF0aCI6Ii82NzUyNjc5LzMxODE4NzkzNC01ZWViNTc0Ny02MjIyLTQ3YWMtOTVkMi0wZDIxZTYxOWIwMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMTExNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1OGFlNmEwMzBhMjRiMzdmNmI2MDRiNDFmN2JiYWIxNTM0MWE5N2JkN2M4NjExMTk3MTY4MTFhZWE3NGIzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H7fN2n85Bd-kBVjLhQGdtcXFRkEBxcUXtLfR_s1lSEU)
> 
> Do you have something like Nginx in the front? There is also a upload limit in it.

I don't use reverse proxy.  Here is the docker compose file that I use :

```
version: '2.1'
services:
  trilium:
    image: zadam/trilium
    container_name: trilium
    networks:
        work:
            ipv4_address: 10.100.0.100
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - TRILIUM_NO_UPLOAD_LIMIT=1
    ports:
      - 7000:8080
    volumes:
      - /data/trilium:/home/node/trilium-data
    restart: always

networks:
    work:
        external: true
```
