### ISSUE TITLE
User data volume empty

### ISSUE THREAD

**Issue by vgnmnky** [zadam/trilium#4812]
### Trilium Version

0.63.7

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Docker  26.1.4 on OpenMediaVault 6.9.16-1 (Shaitan) 

### Description

I'm using Portainer 2.19.5 to deploy the container.

It has been running fine for a few weeks without errors.  However, I've noticed that there is nothing in the local volume specified in my compose file, nor anywhere else I can see.  

I've tried changing the path to ~/trilium-data (and other locations), but when I run that and browse to the Trilium web ui, I get the opening screen with the three options (local, server/sync etc).  Changing the path back brings back my data.

I store everything in home/[USER]/docker/ and this is backed up.  However, now I'm not likely backing up my Trilium data at all.

My stack/compose: 
```
version: '2.1'
services:
  trilium:
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - "8580:8080"
    volumes:
      - /home/myuser/docker/trillium:/home/node/trilium-data
```
(yes, there's a typo in my local data directory name (trillium).  It was while trying to correct that, that I realised the folder was empty.  The internal path has always been as above.)

My main concern now is to ensure I can backup what I have before I load more of my life onto it!

### Error logs

Edit:  My mistake, didn't use full file path, silly mistake (which I managed to avoid on countless other containers...)
