### ISSUE TITLE
FR: option to put the labels at the bottom

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#739]
Hi

Personally I feel like the labels are aligned in a weird way when they are added to a note, and if there are many it is not possible to see all of them at once.

I am wondering why not put them at the bottom of the page and they are aligned side to side and top to bottom as the page length permits like a grid table?  At the moment visually the labels feel a bit awkward given that they eat up the top part of the page in an non aligned way and one has to scroll to see what is going on with them if there are more than three of them.

**Comment by zadam** [comment]
I assume you mean "promoted attributes" since otherwise normal labels are visible only in sidebar or in the dialog ...

I understand that the current setup where they are displayed simply in centered column is not ideal especially with more than few attributes. OTOH it seems to me that simply putting them into grid would make it chaotic and also it's not clear to me how to make this in a responsive way.

This is still an open topic for me and I will work on this in the future ...

**Comment by nil0x42** [comment]
Hello,
The way promoted attributes are shown is indeed still not perfect.

Even the default view has CSS bugs and has a scrolling bar even if i only have 1 promoted attribute.
So so fix it i added come styling on my theme. Makes promoted attributes use a bit less space, and only start scrolling when promoted attributes begin using 30% of note's height.

Here is my CSS related to promoted attributes, if it can be useful to anyone (or even be added to trilium itself):
```css
/*
PROMOTED ATTRIBUTES STYLING
*/

body.theme-my-theme .note-detail-promoted-attributes {
    flex-shrink: 0;
    max-height: 30%;
}
body.theme-my-theme .promoted-attribute-input {
    padding: 0px 3px;
    display: block;
}
body.theme-my-theme .note-detail-promoted-attributes td {
    padding: 1px;
}
```
