### ISSUE TITLE
[UX] Different color for web-links & note-links

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#817]
It would be great to have a different `<a href` color to distinguish links to URLs, and links to internal notes.
Having the same blue for both is confusing.

**Comment by zadam** [comment]
external links are now differentiated by having little arrow at the end. You can further customize the look of external links with CSS (that's how the arrow is added as well):

```CSS
a[href^="http://"]:after, a[href^="https://"]:after {
    color: red;
}
```

**Comment by nil0x42** [comment]
Thank you !

Just for the record, i implemented it like this in my template:
```css
body.theme-my-theme a[href^="http://"], a[href^="https://"],a[href^="http://"]:hover, a[href^="https://"]:hover {
    color: #33eeff;
}
```

I added the `:hover` so color doesn't reset when mouse is over link.
